### ISSUE TITLE
Cannot handle async resource. angularCompilerOptions.enableResourceInlining requires all resources to be statically resolvable.

### ISSUE THREAD

**Issue by about-code** [angular/devkit#1005]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
- node v8.11.2
- npm v5.6.0
- angular v6.0.3
- webpack v4.10.2 with html-loader v0.5.5
- ngtools/webpack v6.0.7, v6.1.0-beta.1 (tried both)

### Repro steps

- Clone [Repo](https://github.com/about-code/ng-mono-sample)
- `git checkout devkit-issue-1005-repro`
- `npm install`
- `npm run build`

What I did in the repo:
- set up an Angular app manually without angular-cli but with webpack and `@ngtools/webpack`
- use `tsconfig.json` with `angularCompilerOptions` and `enableResourceInlining: true`
- write a component *AppComponent.ts* with a template and `templateUrl: "./AppComponent.html"`
- compile app webpack and `@ngtools/webpack`

Debugging:
- edit node_modules/@angular/compiler-cli/src/transformers/inline_resources.js
- add `debugger` statement before `var content = host.loadResource(fileName)` (should be L31)
- `node inspect ./node_modules/.bin/webpack --config=./config/webpack.prod.js`

See below for results from my own debug analysis. 

### The log given by the failure

```
ERROR in : Error: Cannot handle async resource. angularCompilerOptions.enableResourceInlining requires all resources to be statically resolvable.
    at Object.get (/home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/inline_resources.js:33:31)
    at /home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/inline_resources.js:261:43
    at Array.forEach (<anonymous>)
    at updateComponentProperties (/home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/inline_resources.js:232:33)
    at updateDecorator (/home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/inline_resources.js:120:28)
    at /home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/inline_resources.js:95:32
    at Object.visitNodes (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:52846:48)
    at visitor (/home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/inline_resources.js:93:40)
    at visitNodes (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:52846:48)
    at visitLexicalEnvironment (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:52879:22)
    at Object.visitEachChild (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:53173:54)
    at /home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/inline_resources.js:105:23
    at /home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:2892:86
    at reduceLeft (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:2585:30)
    at /home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:2892:42
    at transformRoot (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:67846:82)
    at Object.map (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:1883:29)
    at Object.transformNodes (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:67834:30)
    at Object.emitFiles (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:70664:28)
    at emitWorker (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:74509:33)
    at /home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:74469:66
    at runWithCancellationToken (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:74560:24)
    at Object.emit (/home/user/path/to/my/sample/project/node_modules/typescript/lib/typescript.js:74469:20)
    at defaultEmitCallback (/home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/program.js:89:24)
    at AngularCompilerProgram._emitRender2 (/home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/program.js:369:34)
    at AngularCompilerProgram.emit (/home/user/path/to/my/sample/project/node_modules/@angular/compiler-cli/src/transformers/program.js:231:22)
    at AngularCompilerPlugin._emit (/home/user/path/to/my/sample/project/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:818:49)
    at Promise.resolve.then.then.then (/home/user/path/to/my/sample/project/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:642:54)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Desired functionality
`@ngtools/webpack` should support `enableResourceInlining: true`.

#### Summary
When compiling with `@ngtools/webpack` and `enableResourceInlining: true` template files referenced via `templateUrl`s in NgComponents should be inlined into the component. In order to load the resource **angular/compiler-cli v6.0.3** calls a method [`getResourceLoader`](https://github.com/angular/angular/blob/0bf6fa5b324bb1b1c552b8af51c13871847866a8/packages/compiler-cli/src/transformers/inline_resources.ts#L28) (Permalink) which gets passed an implementation of the [`ResourcesHost` interface defined in the same file](https://github.com/angular/angular/blob/0bf6fa5b324bb1b1c552b8af51c13871847866a8/packages/compiler-cli/src/transformers/inline_resources.ts#L21) (Permalink). It then invokes the method `ResourcesHost#loadResource` which accorrding to its interface definition is permitted to return a `Promise<string> | string`. But in contrast to the interface [`getResourceLoader()` when calling `loadResource()` can only handle a result of `string` (L36)](https://github.com/angular/angular/blob/0bf6fa5b324bb1b1c552b8af51c13871847866a8/packages/compiler-cli/src/transformers/inline_resources.ts#L36). If something else is returned (e.g. a `Promise<string>`) it throws an Error with the non-descriptive message given in the issue title. This is what happens when compiling with `@ngtools/webpack` in the sample repo.

#### Details

Here we begin in `getResourceLoader()` of **angular/compiler-cli**:

```
break in node_modules/@angular/compiler-cli/src/transformers/inline_resources.js:32
 30                 if (fileName) {
 31                     debugger;
>32                     var content = host.loadResource(fileName);
 33                     if (typeof content !== 'string') {
 34                         throw new Error('Cannot handle async resource. ' + PRECONDITIONS_TEXT);
```
We see the error being thrown when the result is not a `string` but a `Promise<string>` for example. When the error occurs `host` is a `TsCompilerAotCompilerTypeCheckHostAdapter` from **angular/compiler-cli**:

```
break in node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:468
 466         TsCompilerAotCompilerTypeCheckHostAdapter.prototype.loadResource = function (filePath) {
 467             if (this.context.readResource)
>468                 return this.context.readResource(filePath);
 469             if (!this.originalFileExists(filePath)) {
 470                 throw compiler_1.syntaxError("Error: Resource file not found: " + filePath);
```

It delegates resource loading to a `context` compiler host and immediately returns the result of `readResource`. When the error occurs `this.context` is a `WebpackCompilerHost` from the **ngtools/webpack**. When stepping into `readResource` we see the [`WebpackCompilerHost` internally uses a `ResourceLoader`](https://github.com/angular/devkit/blob/3fbef3810e63eb28dce78c3cfe83cd478da9d368/packages/ngtools/webpack/src/compiler_host.ts#L428) to read the resource and immediately returns the loader's result as well.

```
break in node_modules/@ngtools/webpack/src/compiler_host.js:335
 333     }
 334     readResource(fileName) {
 335         if (this._resourceLoader) {
 336             // These paths are meant to be used by the loader so we must denormalize them.
 337             const denormalizedFileName = this.denormalizePath(core_1.normalize(fileName));
>338             return this._resourceLoader.get(denormalizedFileName);
 339         }
 340         else {
```

The implementation of the [`resourceLoader#get` in ngtools/webpack](https://github.com/angular/devkit/blob/3fbef3810e63eb28dce78c3cfe83cd478da9d368/packages/ngtools/webpack/src/resource_loader.ts#L143), though, will always return a `Promise<string>`.

```
break in node_modules/@ngtools/webpack/src/resource_loader.js:122
 120     }
 121     get(filePath) {
>122         return this._compile(filePath)
 123             .then((result) => result.source);
 124     }
 ```

So eventually when jumping back to `getResourceLoader()` into line 33 the variable `content` will hold a Promise causing the compilation to fail. Interestingly when looking to an error message in `this._compile()` there's a check whether `filePath` is a TS or JS-File and if so a message states that TS/JS-Files can't be used with `styleUrl`. So there seems to be an implicit assumption that the code is only invoked for `styleUrl` but when in the error occurs it is also invoked for `templateUrl`.

Anyways, the error message produced by the *angular/compiler-cli/src/inline_resources.ts* is misleading to a user of `@ngtools/webpack` because it reads as if the compiler recognizes an attempt to load a component template e.g. via some runtime-`import()` or by some other non-statically resolvable component declaration when the component actually just declared `templateUrl` with a plain string as it is regularly expected for an Angular app.

**Comment by about-code** [comment]
Issue in the Angular-Repo mentioning the same error message but likely in a different context.
https://github.com/angular/angular/issues/23886

**Comment by clydin** [comment]
The plugin automatically inlines all resources internally and leverages the Webpack processing pipeline.  The option `enableResourceInlining` is currently unnecessary and definitely not supported in JIT mode (It may work in AOT mode, however).

**Comment by about-code** [comment]
> It may work in AOT mode

When the error occured I was running an AoT compile so it doesn't seem to be supported in either mode.

> The plugin automatically inlines all resources internally and leverages the Webpack processing pipeline. The option enableResourceInlining is currently unnecessary

Okay, seems like a misunderstanding on my site. I thought I should be able to drop some loader dependencies such as `html-loader` or `css-loader` or `style-loader` once `enableResourceInlining` is supported by `ngc`. This was based on the assumption that any `angularCompilerOption` would work with `@ngtools/webpack` the way they would work when using plain `ngc`. Knowing that `enableResourceInlining` is an exception here, helps. Then I won't put any further efforts into it. Just thought there was a way to simplify webpack configs and reduce the number of third-party dependencies but can live with that.

Thank you @clydin.

**Comment by alexeagle** [comment]
looks like this was resolved, pls open a new issue on angular-cli if there's still a problem
