### ISSUE TITLE
How to override files with merge or branchMerge?

### ISSUE THREAD

**Issue by CarstenLeue** [angular/devkit#1010]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
0.6.5

### Repro steps

In a custom schematic I use this code to copy files from the schematic library to the target project:

```typescript
  const templateSource = apply(url('./app/files'), [
    template({
      ...strings,
      dataDir: 'data/'
    }),
    move(project.root)
  ]);

  return chain([branchAndMerge(chain([mergeWith(templateSource)]))]);
```

This fails if any of the files already exist in the target location. Adding "MergeStrategy.Override" to either mergeWidth or branchAndMerge does not solve this.

### Desired functionality

I would like to be able to specify what happens if copied files already exists in the target location, without producing an error. Either choose to override these files or to ignore the overrides.

How can I do that?

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12088
