### ISSUE TITLE
Post-processing tasks; task runner plugin arch

### ISSUE THREAD

**Issue by dansanderson** [angular/devkit#12]
Schematics should be able to enqueue tasks of various types that are run after file contents have been evaluated and written to disk. There is no expectation that changes can be rolled back if there is an error executing a task, though it might make sense to abort execution of other tasks if any task returns an error.

Tasks could invoke other tasks. These could be enqueued in layers, and each layer sent to a runner for a task type as a batch for efficient execution.

We also need a mechanism to define task types (invocation inputs, runners) outside of the Schematics core code, such as for invoking external tools specific to a developer's environment.

Example use cases: committing to source control automatically, creating bugs in a bug tracker, invoking external text processing tools that cannot integrate with Schematics' staging area for some reason.

**Comment by dansanderson** [comment]
(This is in contrast with invoking an external tool from a Schematic rule that could take text on stdin and return text on stdout, which could conceivably behave like a create/overwrite action for a tree.)

**Comment by clydin** [comment]
Closing as initial implementation is available in version 0.2.0
