### ISSUE TITLE
Optimization fails when webpacks cache options is false

### ISSUE THREAD

**Issue by actra-gschuster** [angular/devkit#136]
I use an emitted ng-cli config and tried to adapt it to use the build-optimizer.
While testing the build always failed until I found out that the build-optimizer only works when webpacks caching is enabled.

In build-optimizer/src/purify/webpack-plugin.js there's the following lines:
```
compilation.assets[fileName]._cachedSource = purifiedSource;
compilation.assets[fileName]._source.source = () => purifiedSource;
```
This code requires "cache: true" to be set in the webpack config as otherwise the assets are ConcatSource objects that don't have "_cachedSource" and "_source" properties resulting in the second line causing an error as "._source" is undefined.

For a fix see PR #135, it's a really simple change with which both caching and non-caching webpack configs are supported.

**Comment by filipesilva** [comment]
Heya, thanks for the reporting this bug. Yeah we shouldn't be using those private fields to set the new source.

Your PR is failing tests though. A better approach would be to not rely at all on private fields... something like https://github.com/angular/angular-cli/blob/4cd714dbcc8ffcd9d0b4a9282d69da5a692d32b7/packages/%40angular/cli/plugins/glob-copy-webpack-plugin.ts#L35-L39.

Can you try that instead?

**Comment by actra-gschuster** [comment]
I updated the files, instead of using private fields it's now instantiating a new CachedSource() with a new RawSource(purified) as param, hope that's correct so far, I've not dug too deep into the code of the devkit so far.

**Comment by filipesilva** [comment]
I couldn't see how your PR failed the CI, but I added a PR to fix this: https://github.com/angular/devkit/pull/137

**Comment by actra-gschuster** [comment]
I used the classes from webpack-sources, the last remaining error was one complaining about webpack-sources being implicitly declared as any.

Your fix seems to be much simpler and cleaner.
You may want to check if webpack really is OK with the plain object or it requires a class instance from webpack-sources, at least the assets pushed into the purifier are ConcatSources objects.

**Comment by filipesilva** [comment]
I actually thought that a using an object was the recommended webpack API (it seems to be for general assets like images) but as far as I can tell, for JS source it really is a ConcatSource like you say.

Can you reopen your PR and also add `@types/webpack-sources` to the dependencies? That should clear your error.

**Comment by actra-gschuster** [comment]
I created a new, clean PR: #138
