### ISSUE TITLE
ngtools/webpack does not emit ngmodule decorator information.

### ISSUE THREAD

**Issue by hans-pragt** [angular/devkit#162]
Resubmitting from https://github.com/angular/angular/issues/18591:

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I am trying to integrate AOT compilation into an existing Angular component library. This library has always been packaged using webpack, so I integrated `ngtools/webpack` into my configuration. After resolving the problem of `ngtools/webpack` not inlining / `require`ing external templates and styles, I was still not able to use the resulting JS module. Whenever I try to run an app using this, I would get an error stating that the module class is missing its `NgModule` decorator.

When examining the generated code, I noticed that `ngtools/webpack` has stripped all decorators from the code.

## Expected behavior

`ngtools/webpack` should keep angular-specific decorators.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by hansl** [comment]
If you use AOT code, you don’t need the decorators anymore, and they only get the bundles larger so we remove them.

Would you have a reproduction repository we could look at?

**Comment by hans-pragt** [comment]
That is true for applications, and it works fine there. But what if you are making a package of reusable components?

**Comment by hansl** [comment]
We don't support building libraries with `ngtools/webpack`. You need to use `ngc` in a separate step. There are tutorials about how to build libraries.

**Comment by filipesilva** [comment]
Closing as this issue seems answered.
