### ISSUE TITLE
Exported downleveled classes don't get picked up by the pure class transform regex

### ISSUE THREAD

**Issue by jasonaden** [angular/devkit#184]
Source code such as:

`export class OuterSubscriber<T, R> extends Subscriber<T> {}`

Will get downleveled as: 
```
export var OuterSubscriber = (function (_super) {
    __extends(OuterSubscriber, _super);
    function OuterSubscriber() {
        _super.apply(this, arguments);
    }
    return OuterSubscriber;
}
```

Our regex testing whether or not to apply the `/** __PURE__ */` annotation doesn't take into account the `export var` prefix on this line.

**Comment by jasonaden** [comment]
This is specific to earlier versions of TypeScript. We found out about this when building rxjs, which is at `2.0.10`. We likely missed this as newer versions of TypeScript will downlevel differently.

Additionally, adding a regex that catches the above downleveled class doesn't end up adding the PURE annotation. The AST based code needs to be adjusted as well to add the annotation.

**Comment by filipesilva** [comment]
I was going to fix this today but @clydin beat me to the punch in #193. The AST code is updated and tested for in his PR.

I should mention `prefix-class` doesn't use a regex to determine whether or not it should be applied, rather it uses a whitelist of known side-effects free libraries (currently just Angular). To apply this transform properly on RxJs you have to import it and apply it on a custom pipeline. 

I can add a parameter to build optimizer to force the side-effect free transforms though. Let me know what you prefer.

**Comment by filipesilva** [comment]
Actually there is a regex that needs to be updated, sorry. Will update in a follow up PR.

**Comment by filipesilva** [comment]
Done in https://github.com/angular/devkit/pull/194. Please let me know if this addresses the RxJs builds.
