### ISSUE TITLE
replace `@class` to `@__PURE__` annotation.

### ISSUE THREAD

**Issue by aitboudad** [angular/devkit#186]
see https://github.com/mishoo/UglifyJS2/issues/2279

**Comment by clydin** [comment]
That’s unfortunately not a safe operation.  All classes are not guaranteed to be side effect free.  The build optimizer currently analyzes the code structure to determine the presence of a downlevel class and further work is being considered to determine the presence of potential side effects to improve the safety of the optimization.

It’s also important to note that the use of pure is a misnomer in this situation and an unnecessary threshold for the intended optimization.
