### ISSUE TITLE
Refelect Polyfills for Angular no longer necessary

### ISSUE THREAD

**Issue by Cito** [angular/devkit#206]
In the file https://github.com/angular/devkit/blob/master/packages/schematics/angular/application/files/__path__/polyfills.ts with the default Polyfills for Angular CLI you have this:

    /** Evergreen browsers require these. **/
    import 'core-js/es6/reflect';
    import 'core-js/es7/reflect';

According to http://kangax.github.io/compat-table/es6/#test-Reflect this seems no longer to be true. By removing these lines, an Angular app can spare some more kB.

**Comment by filipesilva** [comment]
You are right that the evergreen browsers now have Reflect support. Maybe this should be removed.
