### ISSUE TITLE
schematics: new schematic template does not compile

### ISSUE THREAD

**Issue by cexbrayat** [angular/devkit#207]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
macOS Sierra
node v8.6.0
npm v5.3.0
yarn v1.2.0

### Repro steps
Generate a new schematic, and try to compile it (maybe I'm doing this wrong):

```
yarn init
yarn add @angular-devkit/schematics @schematics/schematics
$(yarn bin)/schematics @schematics/schematics:schematic --name ninjasquad
cd ninjasquad
yarn
yarn build
```

### The log given by the failure
```
yarn run v1.2.0
$ tsc -p tsconfig.json
src/my-full-schematic/index_spec.ts(14,63): error TS2345: Argument of type 'Tree' is not assignable to parameter of type 'Tree | undefined'.
  Type 'Tree' is not assignable to type 'Tree'. Two different types with this name exist, but they are unrelated.
src/my-full-schematic/index_spec.ts(19,80): error TS2345: Argument of type 'Tree' is not assignable to parameter of type 'Tree | undefined'.
  Type 'Tree' is not assignable to type 'Tree'. Two different types with this name exist, but they are unrelated.
    Property 'root' is missing in type 'Tree'.
src/my-other-schematic/index_spec.ts(12,64): error TS2345: Argument of type 'Tree' is not assignable to parameter of type 'Tree | undefined'.
  Type 'Tree' is not assignable to type 'Tree'. Two different types with this name exist, but they are unrelated.
src/my-schematic/index_spec.ts(12,58): error TS2345: Argument of type 'Tree' is not assignable to parameter of type 'Tree | undefined'.
  Type 'Tree' is not assignable to type 'Tree'. Two different types with this name exist, but they are unrelated.
error Command failed with exit code 1.
```

### Desired functionality
Compilation fails and probably should not

**Comment by BenjaminDobler** [comment]
I have the same issue. Is there a known workaround or are we doing somethong wrong?

**Comment by hansl** [comment]
This is most definitely a yarn issue. Not urgent but I'll look at it soon.

**Comment by BenjaminDobler** [comment]
I`m actually doing the same as @cexbrayat but with npm. So does not seem to be limited to yarn.

**Comment by hansl** [comment]
Then you should see a different error, which is fixed by #246.

**Comment by BenjaminDobler** [comment]
It looks pretty much like the same error:
`src/my-full-schematic/index_spec.ts(14,63): error TS2345: Argument of type 'Tree' is not assignable to parameter of type 'Tree | undefined'.
  Type 'Tree' is not assignable to type 'Tree'. Two different types with this name exist, but they are unrelated.
src/my-full-schematic/index_spec.ts(19,80): error TS2345: Argument of type 'Tree' is not assignable to parameter of type 'Tree | undefined'.
  Type 'Tree' is not assignable to type 'Tree'. Two different types with this name exist, but they are unrelated.
    Property 'branch' is missing in type 'Tree'.
src/my-other-schematic/index_spec.ts(12,64): error TS2345: Argument of type 'Tree' is not assignable to parameter of type 'Tree | undefined'.
  Type 'Tree' is not assignable to type 'Tree'. Two different types with this name exist, but they are unrelated.
src/my-schematic/index_spec.ts(12,58): error TS2345: Argument of type 'Tree' is not assignable to parameter of type 'Tree | undefined'.
  Type 'Tree' is not assignable to type 'Tree'. Two different types with this name exist, but they are unrelated.`

But yeah i`m just trying to get into schematics so it could be something stupid on my end.

**Comment by BenjaminDobler** [comment]
Strange now i setup a new project and it seems to work fine.
Just in case here are the steps i did:
npm init
npm i @angular-devkit/schematics @schematics/schematics --save-dev
node_modules/bin/schematics @schematics/schematics:schematic --name action1
cd action1
npm install
npm run build

**Comment by hansl** [comment]
I just did a release.

**Comment by BenjaminDobler** [comment]
Awesome thanks for your fast help and your great work!

**Comment by cexbrayat** [comment]
Issue is fixed with last release, thx @hansl
