### ISSUE TITLE
Combine two schematics collections

### ISSUE THREAD

**Issue by deanmiller** [angular/devkit#208]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area

@angular/schematics

### Desired functionality

I would like to be able to combine two schematics. Is this possible?

I would like to build some schematics for code generation for my use cases that I plan to apply on top of another schematic. This way I can update each schematics code bases independently.

Example:
ng new --collection=nrwl/schematics+my/schematics

**Comment by filipesilva** [comment]
See https://github.com/angular/devkit/issues/34 for details about this feature. There's information there about how this can currently be done.
