### ISSUE TITLE
Offer a schematics API for doing npm/yarn installs

### ISSUE THREAD

**Issue by StephenFluin** [angular/devkit#216]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] feature request
```

### Area
```
- [x] schematics
```

I would like to be able to call a function within schematics, and have schematics install via my chosen package manager. This would also allow tools like StackBlitz to override / patch these methods and perform their own package installation / setup.

**Comment by hansl** [comment]
Duplicate of #12?
