### ISSUE TITLE
Schematics poor performance: Tree includes node_modules

### ISSUE THREAD

**Issue by sasxa** [angular/devkit#266]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
Performance of `schematics.call()` is poor and there is a possible memory leak in `registerOptionsTransform`.
### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

    "@angular-devkit/schematics": "0.0.35"

### Repro steps

I have a method for generating blueprints based on https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics/bin/schematics.ts:

```typescript
export class SchematicsManager {
  host = new NodeModulesEngineHost();
  engine = new SchematicEngine(this.host);
  config = { /* ... */ };

  generateBlueprint(collection, blueprint) {
    console.log((`Executing command: ng generate ${ blueprint }`));

    this.host.registerOptionsTransform((schematic: any, options: {}) => {
      const transformed = {
        ...this.defaults(schematic, options),
        ...this.values(schematic, options),
      };

      console.log(`registerOptionsTransform`);
      return transformed;
    });

    const _collection = this.engine.createCollection(collection);
    const schematic = _collection.createSchematic(blueprint);

    const dryRunSink
      = new DryRunSink(this.config.workspaceRoot, true);
    const fsSink
      = new FileSystemSink(this.config.workspaceRoot, true);
    const fsHost
      = new FileSystemHost(this.config.workspaceRoot);
    const tree$
      = of(new FileSystemTree(fsHost))

    dryRunSink.reporter.subscribe((event: DryRunEvent) => {
      /* ... */
    });

    schematic.call({}, tree$)

      .do(() => console.time('schematics.call()'))

      .map((tree: Tree) => Tree.optimize(tree))
      .concatMap((tree: Tree) => {
        return dryRunSink
          .commit(tree)
          .ignoreElements()
          .concat(of(tree));
      })
      .concatMap((tree: Tree) => {
        return dryRun || error
          ? of(tree)
          : fsSink
            .commit(tree)
            .ignoreElements()
            .concat(of(tree));
      })

      .do(() => console.timeEnd('schematics.call()'))

      .subscribe({
        error: (error) => { /* ... */ },
        complete: () => { /* ... */ }
      });

  }
}
```

### The log given by the failure

When I call it to generate a few classes with `generateBlueprint('@schematics/angular', 'class')` this is the log:

```
Executing command: ng generate class
registerOptionsTransform
schematics.call(): 87.711ms
CREATE /src/app/x.ts (19 bytes)

Executing command: ng generate class
registerOptionsTransform
registerOptionsTransform
schematics.call(): 74.361ms
CREATE /src/app/x.ts (19 bytes)

Executing command: ng generate class
registerOptionsTransform
registerOptionsTransform
registerOptionsTransform
schematics.call(): 76.646ms
CREATE /src/app/x.ts (19 bytes)
```
It takes 7-9 seconds to generate this class, probably because the tree contains whole `node_modules` folder.

Also `host.registerOptionsTransform()` is called +1 times for each call. I tried unsubscribing in various places, using `take(1)` and some other things, but nothing worked. It seams there is a subscription somewhere that isn't cleared...

### Desired functionality

If I set different root for the `FileSystemHost`:

```typescript
    const fsHost
      // = new FileSystemHost(this.config.workspaceRoot);
      = new FileSystemHost(join(this.config.workspaceRoot, 'src/app'));
```
schematics are generated much faster 0.4-1s:
```
Executing command: ng generate class
registerOptionsTransform
schematics.call(): 16.902ms
CREATE /src/app/x.ts (19 bytes)

Executing command: ng generate class
registerOptionsTransform
registerOptionsTransform
schematics.call(): 9.312ms
CREATE /src/app/x.ts (19 bytes)

Executing command: ng generate class
registerOptionsTransform
registerOptionsTransform
registerOptionsTransform
schematics.call(): 4.560ms
CREATE /src/app/x.ts (19 bytes)
```
In my project I imported `.angular-cli.json` and used `apps[ ... ].root` as `FileSystemHost` root. Maybe something similar would be good for schematics too- using `Tree` without `node_modules`. 

Any idea what could be causing multiple calls to `host.registerOptionsTransform()`?

### Mention any other details that might be useful

A bit off-topic question: **How are the paths for files generated?** All schematics have `name`, `path`, `sourceDir`, `appRoot` properties, but no descriptions and I couldn't find exactly where they are used.

**Comment by clydin** [comment]
For the performance, can you try again with the latest versions?

For the `registerOptionsTransform` issue, that call should only happen once when the host is initialized.  In the code above it is being called on every generate and causing an additional transform function to be registered per generate call.

**Comment by sasxa** [comment]
@clydin With `0.0.36` I'm getting a desired result, `schematics.call()` takes about a second. This is great as it will solve some other problems I had with non-root `FileSystemHost`. Thanks!

**Comment by sasxa** [comment]
@clydin  `service` schematic is still slow, all others work as expected.

**Comment by clydin** [comment]
Filtering currently causes a full walk of the underlying tree.  For most schematics this is typically only done on the source tree and since source trees are generally small,  there is no noticeable performance impact.
The Angular service schematic, however, filters on the destination tree which can cause a performance problem for large file system trees.

**Comment by sasxa** [comment]
@clydin Thanks for the clarification.
