### ISSUE TITLE
Display dry-run generated files contents in verbose mode

### ISSUE THREAD

**Issue by wardbell** [angular/devkit#286]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Desired functionality

Current DryRun lists the files that will be created/touched but not their contents. 

Proposing a verbose variant that would output the files themselves. The developer could scroll through the console log or (more likely) capture the stdout to file.

Maybe this happens with the flag combo `--dry-run --verbose`

**Comment by ssilvert** [comment]
+1

Usually, you are just working on the output of one file at a time.  So perhaps another option would be to specify a single file.

--verbose would dump all modified files
--verbose=myPath would dump a single file

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12155
