### ISSUE TITLE
A flag to display a list of available parameters

### ISSUE THREAD

**Issue by sebawita** [angular/devkit#311]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Desired functionality
Currently the only way to check the available parameters for a schematics is by looking into its json schema file.
It would be great to have a way in the CLI to display the list of params, like this:
```schematics @schematics:schematic --schema```

**Comment by ssilvert** [comment]
+1

It seems like the proper flag for this would be --help.  Of course, --help is used for something else now, but perhaps schema help should be incorporated into that.

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12152
