### ISSUE TITLE
Custom schematic returns with Error: Path "/README.md" does not exist.

### ISSUE THREAD

**Issue by rtuk** [angular/devkit#322]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
node --version
v6.9.4

npm --version
5.5.1

Globally installed npm modules:

@angular-devkit/core@0.0.22
@angular-devkit/schematics@0.0.41
@angular/cli@1.6.0
@schematics/schematics@0.0.10
rxjs@5.5.5

### Repro steps
mkdir schematics
cd schematics
git clone git@github.com:angular/devkit.git
schematics @schematics/schematics:blank --name test-angular-schematics
cd test-angular-schematics
cp -pvr ../devkit/packages/schematics/angular/* src/
npm install
npm install --save rxjs

Fix types for options in class, component, directive, enum, guard, interface, module, pipe, service, universal

npm run build
npm link

ng new --verbose --routing=true --style=scss --collection=@test/angular-schematics test

### The log given by the failure
Error: Path "/README.md" does not exist.
Path "/README.md" does not exist.

### Desired functionality
new angular project based on the copied default angular schematic

**Comment by Brocco** [comment]
There is a schematic you can run to create a schematics project.

install @angulat-devkit/schematics & @schematics/schematics globally

Run:
```
schematics @schematics/schematics:schematic --name=test
or for a blank project
schematics @schematics/schematics:blank --name=test
```

**Comment by rtuk** [comment]
The idea is to take the default angular schematic as a basis to add some custom code we use in all of our projects, this also includes a change in indentation (2 spaces to 4 spaces)  in the default schematic.
In order to allow us to do this we have to have the base angular schematic as a basis, which should work. In the previous version this solution resulted in "tree.branch is not a function", because the schematic was globally installed, this problem has since been fixed, however now, with the new versions, the result of running the custom schematic based on the default angular schematic returns with the error "Path "/README.md" does not exist."

Also, no reference to where this error is caused is returned, not even when running "ng new" with the verbose option

**Comment by Hotell** [comment]
Hi everyone, why is this closed ? this issue is still present

![image](https://user-images.githubusercontent.com/1223799/37570356-2ab7da58-2aef-11e8-944f-f243e233ca14.png)

```
Angular CLI: 1.7.3
Node: 8.10.0
OS: darwin x64
```
