### ISSUE TITLE
ng generate universal should add dist-server to .gitignore

### ISSUE THREAD

**Issue by beeman** [angular/devkit#323]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

macOS High Sierra
```
❯ node --version 
v8.9.1
❯ npm --version
5.5.1
```

### Repro steps

The dist-server folder does not get ignored so a dev might commit it to the repo.

```
ng new my-app
cd my-app
ng generate universal server
npm install
ng build --app server
git git status # this contains the folder dist-server which should be ignored
```

### The log given by the failure

N/A

### Desired functionality

The `dist-server` folder should be ignored.

**Comment by Brocco** [comment]
Possible alternative: change `dist-server` and other dist folders to be sub-directories under `dist`.

**Comment by beeman** [comment]
In my manual setups I used `dist/browser` and `dist/server`.

I also gave the initial app the `name` and `platform` properties and set them to `browser`, just to make the 2 app definitions more in line.
