### ISSUE TITLE
ng generate universal should not define 'polyfill' in angular-cli.json

### ISSUE THREAD

**Issue by beeman** [angular/devkit#324]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

macOS High Sierra
```
❯ node --version 
v8.9.1
❯ npm --version
5.5.1
```

### Repro steps

The new universal app that is generated in `.angular-cli.json` contains a reference to `src/polyfill.ts`, which does not need to be there.

```
ng new my-app
cd my-app
ng generate universal server
```

### The log given by the failure

N/A

### Desired functionality

The `"polyfills": "polyfills.ts"` entry from the server app in `.angular-cli.json` can go.

**Comment by hansl** [comment]
@Brocco @vikerman could you validate this and fix?
