### ISSUE TITLE
Add change log for `@angular-devkit/build-optimizer`

### ISSUE THREAD

**Issue by emilio-martinez** [angular/devkit#341]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Desired functionality
Given that `@angular-devkit/build-optimizer` can be used as a standalone, I believe it should have a changelog. There's no indication of what has changed, nor are releases tagged to at lease see the commits that are included in a version diff.

**Comment by filipesilva** [comment]
I think this is a problem with overall packages in the devkit. 

@hansl it seems we had a changelog once (https://github.com/angular/devkit/releases) but only that one. We should add detailed changelogs on releases.

**Comment by emilio-martinez** [comment]
@filipesilva @hansl pinging on this item again. This would be immensely helpful.

I understand that when used with Angular CLI this is more seamless, but when used with a non-Angular CLI Webpack setup using these packages somewhat feels like flying blind.

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12151
