### ISSUE TITLE
build-optimizer/webpack-loader.ts imports undeclared dependency "webpack"

### ISSUE THREAD

**Issue by brian428** [angular/devkit#376]
`webpack-loader.ts` includes the line `import * as webpack from 'webpack';`, but `webpack` is not declared as a dependency for the build-optimizer package. Should this be using `webpack-sources` (which is declared)?

**Comment by clydin** [comment]
It's used for type information during development which is why it's not referenced as a dependency.  The import is elided by the TypeScript compiler.
