### ISSUE TITLE
Build-optimizer 0.0.37 creates IIFE with wrong this context 

### ISSUE THREAD

**Issue by Ristaaf** [angular/devkit#381]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Versions

node: v8.9.4
npm: 5.6.0

build-optimizer: 0.0.37

### Repro steps

TypeScript/JavaScript code
```
public setValue(value: any): any {
    this.value = value;
    const updates: any = {};
    updates[this.entryName] = value;

    this.viewStateService.updateState(updates);

    this.valueChange$.next(value);
}
```

gives this non working code with 0.0.37 (the this keyword in this.entryName is the problem)
```
e.prototype.setValue = function(e) {
    this.value = e,
    this.viewStateService.updateState(function() {
        var t = {};
        return t[this.entryName] = e,
        t
    }()),
    this.valueChange$.next(e)
}
```

in 0.0.36 the output was this which works fine:
```
e.prototype.setValue = function(e) {
    this.value = e;
    var t = {};
    t[this.entryName] = e,
    this.viewStateService.updateState(t),
    this.valueChange$.next(e)
}
```

### The log given by the failure

ERROR TypeError: Cannot read property 'entryName' of undefined

### Desired functionality

Code that works, either by making sure "this" has the correct context, or by not IIFE ing the function call!

### Mention any other details that might be useful

This is using Angular-CLI (1.6.4), not sure if that matters, downgrading build-optimizer to 0.0.36 fixes the issue.

**Comment by clydin** [comment]
This looks like an overzealous enum optimization.  The example code is erroneously being identified as a downlevel enum.  Looking into it now.

**Comment by clydin** [comment]
@briantq just did a quick test and the build optimizer doesn't appear to modify the downlevel code for that example so I don't think it is related.

**Comment by Ristaaf** [comment]
Great work, and quick fix (and release too!)
