### ISSUE TITLE
(schematics documentation) Add more sources

### ISSUE THREAD

**Issue by MonsieurMan** [angular/devkit#402]
Hello, I looked over the project because it seemed to me like I could use it for a project I have in mind and couldn't really find a simple dive in introduction.  
Until I found the [meetup presentation introducing it](https://youtu.be/LZxbDp1nOVo?t=491).
I think it should be added to the head of the readme to help people understand the package as of now, it really helped me understand quickly and I know we're going to use it for at least two projects.  

If you know of any information sources you produced like this one I think you should point them out in the head of the readme or something.   

Anyway, keep up the good job, I feel like front end development is getting healthier thanks to the trust you and the react community are creating !

**Comment by filipesilva** [comment]
@hansl I think you were working on some more Schematics docs, are they available yet?

**Comment by Toxicable** [comment]
There's this here
https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2
and the source code here is well commented on how to use schematics programtically
https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics_cli/bin/schematics.ts

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12149
