### ISSUE TITLE
For polyfill es7/reflect, it should be mentioned that tests are not run in AOT mode

### ISSUE THREAD

**Issue by fredgate** [angular/devkit#408]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
angular CLI 1.6.4

### Repro steps
Use AOT to serve and build the application.

In the `polyfills.ts` file, comment the `import 'core-js/es7/reflect';` line as it is mentioned that :
```
/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
// import 'core-js/es7/reflect';
```

Then execute unit tests. Tests where a provider (the system under test, or any other class) has a injected dependency will fail with a message indicating that it can resolve all parameter for the class. It is not because its dependencies are not registered in the testing module, but because it can not read metadata of the class and so determine the dependant classes.

### The log given by the failure
```
Error: Can't resolve all parameters for MyService: (?). in http://localhost:9876/_karma_webpack_/vendor.bundle.js (line 20595)
syntaxError@http://localhost:9876/_karma_webpack_/vendor.bundle.js:20595:34
../../../compiler/esm5/compiler.js/CompileMetadataResolver.prototype._getDependenciesMetadata@http://localhost:9876/_karma_webpack_/vendor.bundle.js:35802:35
```

### Desired functionality
The `polyfills.ts` should mention for the _es7/reflect_ polyfill that unit tests are not run in AOT mode.

**Comment by fredgate** [comment]
angular/angular#21440

**Comment by fredgate** [comment]
I can propose a pull request.

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12148
