### ISSUE TITLE
Ensure git repository initialization task runs before npm install

### ISSUE THREAD

**Issue by josuerios** [angular/devkit#447]
I'm creating a schematic where I use husky to set some git hooks. When I run it the hooks can't be set correctly since the git repository is not yet initialized.

```
- [x] bug report
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
nodejs version: v8.9.3
npm version: 5.5.1
OS: macOS El Capitan
```bash
npm ls -g -depth 0

├── @angular-devkit/schematics-cli@0.4.0
├── @angular/cli@1.7.0
├── bower@1.8.2
├── bower-nexus3-resolver@1.0.2
├── gulp@3.9.1
├── gulp-cli@2.0.1
├── npm@5.5.1
├── prettier@1.10.2
├── serve@6.4.9
├── tslint@5.9.1
└── typescript@2.6.2
```

### Repro steps
1- Create a schematic for an application that uses husky to setup git hooks (add it to package.json).
2- Run the schematic.

Sample repo: https://github.com/josuerios/schematic-sample

### The log given by the failure
When running ```npm install``` task it gives the following message:

![image](https://user-images.githubusercontent.com/9700939/36383984-86478f14-156c-11e8-8477-c0e7d6d85e69.png)

Then, when finished:

![image](https://user-images.githubusercontent.com/9700939/36384072-cc440c68-156c-11e8-865c-32e3a1a32059.png)

### Desired functionality
Git repository should be initialized first, before ```npm install``` runs

**Comment by clydin** [comment]
The order is intentional to capture any artifacts created during the package install (e.g., package lock files).

**Comment by josuerios** [comment]
Hi @clydin, you could do the following:

1. init repo (git init)
2. run npm install
3. run git add .

hooks will set correctly and all artifacts will be captured.
