### ISSUE TITLE
Purify should annotate the top level function call before parenthesis.

### ISSUE THREAD

**Issue by mhevery** [angular/devkit#45]
Consider this line
```TypeScript
export const Injectable: InjectableDecorator = <InjectableDecorator>makeDecorator('Injectable');
```

The cast `<InjectableDecorater>` causes this code in tsickle
```
export const Injectable = (/**@type{InjectableDecortaro}*/makeDecorator('Injectable'));
```

This generates  (notice the parenthesis)

```TypeScript
var Injectable = (/*@__PURE__*/ makeDecorator('Injectable'));
````

Which than makes it retained as parenthesis defeats the `@__PURE__`. This than retains large portion of code.

**Comment by filipesilva** [comment]
@mhevery is this transformation happening with `@angular-devkit/build-optimizer`?

I tried feeding it 
```
export const Injectable = (/**@type{InjectableDecortaro}*/makeDecorator('Injectable'));
```

and it outputs
```
export const Injectable = /*@__PURE__*/ (makeDecorator('Injectable'));
```

Which seems to be what you want.

**Comment by IgorMinar** [comment]
I've just seen this problem when looking through the webpack output of aio.
You can check there or I can find it when I'm on my laptop.

**Comment by hansl** [comment]
We did some upgrades to build-optimizer last week, could those have fixed this?

**Comment by filipesilva** [comment]
I tried finding it in AIO, by running `ng build --environment=stable -aot -bo --no-sourcemap` and searching `dist/main.bundle.js` for `(/*@__PURE__*/ ` but could not find with the comment only inside the parenthesis. 

I found a few with comment inside and outside though:
```
var reflector = /*@__PURE__*/ new Reflector(/*@__PURE__*/ new ReflectionCapabilities());

var _MdButtonMixinBase = /*@__PURE__*/ mixinColor(/*@__PURE__*/ mixinDisabled(MdButtonBase));

var _MdCheckboxMixinBase = /*@__PURE__*/ mixinColor(/*@__PURE__*/ mixinDisabled(MdCheckboxBase), 'accent');

    'yMMMdjms': /*@__PURE__*/ datePartGetterFactory(/*@__PURE__*/ combine([
        /*@__PURE__*/ digitCondition('year', 1),
        /*@__PURE__*/ nameCondition('month', 3),
        /*@__PURE__*/ digitCondition('day', 1),
        /*@__PURE__*/ digitCondition('hour', 1),
        /*@__PURE__*/ digitCondition('minute', 1),
        /*@__PURE__*/ digitCondition('second', 1),
    ])),
```

**Comment by IgorMinar** [comment]
@filipesilva that's correct. nested calls should have the annotation at each level of nesting.

**Comment by kara** [comment]
Misko removed the problematic casts in https://github.com/angular/angular/commit/b7a6f52d59c286ece0512fd407d4b9f2ffd9ae1d, so we shouldn't expect to see anything in the outputs.  That said, when I re-add some of the original code causing issues, I see this now:

```js
var Injectable = /*@__PURE__*/ (makeDecorator('Injectable'));
```

Seems like it's fixed.
