### ISSUE TITLE
ng generate service --module=

### ISSUE THREAD

**Issue by sharathc10** [angular/devkit#469]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Area
```
- [ ] devkit
- [ x] schematics
```

**Comment by filipesilva** [comment]
Closing as this issue seems to have been opened by mistake since it has no details.

**Comment by sharathc10** [comment]
Oops - sorry about that.  I am not sure what happened here.  I will open a new one.
