### ISSUE TITLE
Export schematics rules so they can be chained with custom once

### ISSUE THREAD

**Issue by alan-agius4** [angular/devkit#515]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Area
```
- [ ] devkit
- [X] schematics
```

## Desired functionality
At the moment, AFAIK, there is no way to chain, schematics from angular together with your own schematics.

It would be nice if and provide more flexibility for developers when some is developing a custom schematic which chains with an angular schematic. Example, I have custom schematics that does something on top of what create component does. I still want to perform the changes in the same tree, so I don't up with an invalid state if there is an error.

I see the usage something like this.

**Custom schematic**
```ts
import { createComponent, ComponentOptions } from '@schematics/angular';

export default function (options: ComponentOptions): Rule {
  return chain([
    createComponent(options),
    myOwnCustom(options),
  ]);
}

function myOwnCustom(options: ComponentOptions): Rule { }
```

I'd glad do a PR, if you agree.

**Comment by james-schwartzkopf** [comment]
Are you aware of externalSchematic?
https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2#8353

**Comment by alan-agius4** [comment]
Um, no thanks for that :)
