### ISSUE TITLE
ngo is removing non-angular decorators

### ISSUE THREAD

**Issue by aksyonov** [angular/devkit#53]
#### Versions
```
@angular/cli: 1.3.0-rc.3
node: 8.2.1
os: linux x64
@angular/animations: 4.3.0
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.0
@angular/compiler: 4.3.0
@angular/compiler-cli: 4.3.0
@angular/core: 4.3.0
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.3.0
@angular/http: 4.3.0
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.0
@angular/platform-browser-dynamic: 4.3.0
@angular/router: 4.3.0
```
#### Repro steps

1. Use [lodash-decorators](https://github.com/steelsojka/lodash-decorators) or some custom decorators in components.
2. Build app using `ng build --prod --aot --no-sourcemap --build-optimizer`.

#### Observed Behavior

After building app all decorators are removed.

#### Expected Behavior

Keep non-angular decorators.

**Comment by filipesilva** [comment]
@aksyonov I'd like to take this on but need an exact repro so I can properly investigate.

Can you give me a block of code that uses `lodash-decorators` I can add to a Angular CLI project to see this?

Ideally the code would have some runtime behaviour that I can validade in addition to just comparing source.

**Comment by aksyonov** [comment]
Here is the test project - https://github.com/aksyonov/angular-lodash-decorators-test.

When you start it you should see simple table like:
![image](https://user-images.githubusercontent.com/2206553/28888728-601215f2-77ca-11e7-8351-2506d21022c6.png)

When you run `npm run build` and open built project you won't see the table, but you'll see next messages in console:
![image](https://user-images.githubusercontent.com/2206553/28888818-b074fc58-77ca-11e7-8863-34ca13db9c15.png)

Because [bind decorator](https://github.com/aksyonov/angular-lodash-decorators-test/blob/c0bd27b25d706884384dafad507255f7f735c100/src/app/app.component.ts#L22) was removed.

**Comment by filipesilva** [comment]
I had a go at reproducing this. I don't think it's the `@angular-devkit/build-optimizer` causing it as much as something in the `--prod` flag of Angular CLI. 

If you do `ng serve --aot --build-optimizer` the example works. But `ng serve --prod --build-optimizer` breaks it.

I don't know what changed, but latest `@angular/cli` master does not suffer from this. So something changed and fixed this scenario. No idea what though. Maybe a dependency.

Anyway, next release of Angular CLI RC should fix it. Let me know if you're still seeing this then.

**Comment by aksyonov** [comment]
Updating to `@angular/cli: 1.3.0-rc.5` fixed the issue. Thanks.

**Comment by filipesilva** [comment]
Awesome, good to hear!
