### ISSUE TITLE
CLI schematics regression: missing rules in tslint.json

### ISSUE THREAD

**Issue by cexbrayat** [angular/devkit#570]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Repro steps

Just generate a project with CLI `6.0.0-beta.7`.
The `tslint.json` file now lacks the `directive-selector` and `component-selector` rules.

### Desired functionality

It should still have the rules.

### Mention any other details that might be useful

See the difference between beta.6 and beta.7 https://github.com/cexbrayat/angular-cli-diff/compare/6.0.0-beta.6...6.0.0-beta.7

**Comment by cexbrayat** [comment]
I just realized that the `prefix` option is completely ignored too when generating a new project. Is it getting removed or is it not yet implemented?

**Comment by filipesilva** [comment]
Regarding the selector rules being gone, that is a bug of sorts. I removed them because now you can generate apps and libraries, and linting would fail right after doing so.

The right behaviour is for app/lib generation to add those prefixes to tslint.

**Comment by chrste90** [comment]
I would like to look into it but have some questions first:

1. There are currently no prefixes in angular.json for apps or libs. Should these be added back as well?
2. And how should it work if there are different prefixes for each app/lib? Then the rule would be added multiple times with different values. Does this work? Or is it possible to add more than one prefix to the rules?

**Comment by chrste90** [comment]
I like the idea of different tslint configs for each app/lib.

Should the `ng lint` command find the appropriate config at runtime or should this be added to `angular.json`?

**Comment by filipesilva** [comment]
The lint builder already picks the closes `tslint.json` file actually. So as long as there is one extending the base one, it should work.

**Comment by chrste90** [comment]
Okay. So the only thing needed is to update the schematics to create a new tslint file which extends the base tslint and adds the two missing rules? (Aside from the missing prefix in angular.json)

**Comment by sfabriece** [comment]
not sure if this  should go here: 

currently new projects have an rxjs blacklist in tslint.

the rxjs blacklist should be removed for v6, sincethe recommended way to import creators is directly from `'rxjs'`

**Comment by chrste90** [comment]
It ist already fixed in master and should be in the next release: https://github.com/angular/devkit/pull/600

**Comment by sfabriece** [comment]
thanks @chrste90
