### ISSUE TITLE
tslint: remove "rxjs" from import-blacklist

### ISSUE THREAD

**Issue by prabh-62** [angular/devkit#585]
### Bug Report or Feature Request
```
- [x] bug report
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

```bash
> # node --version
  v9.10.0
```

```bash
> yarn --version
  1.5.1
```

```bash
Angular CLI: 6.0.0-beta.7
Node: 9.10.0
OS: darwin x64
Angular: 6.0.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-beta.7
@angular-devkit/architect: 0.0.8
@angular-devkit/build-optimizer: 0.4.7
@angular-devkit/build-webpack: 0.0.8
@angular-devkit/core: 0.4.7
@angular-devkit/schematics: 0.4.7
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.7
@schematics/angular: 0.4.7
@schematics/package-update: 0.4.7
typescript: 2.7.2
webpack: 4.1.1
rxjs: 6.0.0-beta.3
tslint: 5.9.1
```

```bash
> sw_vers
  ProductName:	Mac OS X
  ProductVersion:	10.13.3
  BuildVersion:	17D102
```

### Repro steps
```bash
> ng new hello-angular

```
- Edit `app.component.html` file
<img width="571" alt="rxjs-tslint" src="https://user-images.githubusercontent.com/13006107/38063404-025e7550-32c7-11e8-9a09-095fb76c5f17.png">

- Error: `[tslint] This import is blacklisted, import a submodule instead (import-blacklist)`

 <img width="300" src="https://pbs.twimg.com/media/DZaoAMUUQAAh47F.png" alt="tslint-rule">

### Desired functionality
Please remove `rxjs` from import-blacklist rule

I could have sent a PR if I knew where to edit tslint rules.

**Comment by kylecordes** [comment]
I'm using this import-blacklist with rxjs forward-compat, to prepare big piles of code for A6/Rx6.

```
    "import-blacklist": [
      true,
      "rxjs/Rx",
      "rxjs/Observable",
      "rxjs/Observer",
      "rxjs/Subject",
      "rxjs/observable/defer",
      "rxjs/observable/merge",
      "rxjs/observable/of",
      "rxjs/observable/timer",
      "rxjs/observable/combineLatest",
      "rxjs/add/observable/combineLatest",
      "rxjs/add/observable/of",
      "rxjs/add/observable/merge",
      "rxjs/add/operator/debounceTime",
      "rxjs/add/operator/distinctUntilChanged",
      "rxjs/add/operator/do",
      "rxjs/add/operator/filter",
      "rxjs/add/operator/map",
      "rxjs/add/operator/retry",
      "rxjs/add/operator/startWith",
      "rxjs/add/operator/switchMap",
      "rxjs/observable/interval",
      "rxjs/observable/forkJoin"
    ],
```

It's not complete, but picks up the great majority of shortly-becoming-legacy rxjs imports.

I wish the blacklist message wasn't "import a submodule instead" - because the blacklist idea is useful far outside of "import a submodule instead".

**Comment by caroso1222** [comment]
Not sure if I'm missing something, but you're not supposed to import anything from the main `'rxjs'` entrypoint. This generally causes problems on tree shaking. You're supposed to use deep imports instead:

```typescript
import { of } from 'rxjs/observable/of';
```

That's the reason why the import from 'rxjs' is generally blacklisted from every other `tslint.json`.

**Comment by kylecordes** [comment]
@caroso1222 With RxJS 6.0, or with `"rxjs": "5.6.0-forward-compat.2",`, it is a new world! The thing you described above, that was true until quite recently. But now, RxJS imports are streamlined as one might have imagined from the beginning. This is using ES modules with full tree shaking support, just as efficient as the old way but without the manual work. Here is an example of modern (v6) RxJS import style:

```
import { Observable, BehaviorSubject, interval, of } from 'rxjs';
import { delay, map, share, take } from 'rxjs/operators';
```

**Comment by caroso1222** [comment]
Whoa, didn't know that! Thanks for the clarification @kylecordes.
