### ISSUE TITLE
Regression: no more smart defaults for generate commands in 6.0-rc.0

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/devkit#615]
### Bug Report or Feature Request 
```
- [x] bug report -> please search issues before submitting
```

### Area
```
- [x] devkit
- [x] schematics
```

### Versions
CLI v6.0.0-rc.0

### Repro steps
```
ng new hello --inline-template
ng g component hello
```

Generate a component with an external template instead of an inline one.

### Desired functionality
generate commands should continue as in CLI 1 to use defaults options chosen when creating the app. This feature seems to have completely disappear in CLI 6.0 and it would be a huge step back.

@hansl @Brocco @filipesilva

**Comment by filipesilva** [comment]
Yes this is an unintended regression. Those options should still be set in a project. 

Also thank you for testing the RC!

**Comment by Brocco** [comment]
This is not a regression, creating a project using `--inline-template` did not cause all other components generated for that project to use inline templates. If that behavior is something you'd like to see, please create a feature request issue.

Thanks!

**Comment by cyrilletuzi** [comment]
@Brocco Are you serious? Of course it was. First because it's the only thing that makes sense (if I create a project with `--inline-template`, it's not just to have an inline template in `AppComponent`, it means of course I'll use inline templates everywhere), and second because I was the one who did the PR (#196).

And to be clear, it's not just about `--inline-template`, it's also `skip-tests`, and all the options that were possible under the `defaults` property of `.angular.cli.json`, which has completely disappeared from the new schemas.

Dropping this feature would mean existing projects would now have to add a nightmare of options when doing `ng g` to keep their previous behavior and match the project choices. (And, additionally, it would not be very respectful of work done by contributors.)

**Comment by hansl** [comment]
These options are still there, they're just not properly saved when creating a new project. I agree that at least what we supported is a regression, but this is not blocking for 6.0. Let's keep this issue opened (and fix it in 6.1).

**Comment by cyrilletuzi** [comment]
Could you point me to where to save them manually in the new `angular.json`? Otherwise my next Angular course will be a nightmare.

**Comment by cyrilletuzi** [comment]
Btw, saying "it's a regression" and "it's not blocking for final" is a really strange way to manage an open source project. Any other _really_ open source project wait for things to be ready before releasing final, instead of sticking to an internal and rigid agenda (yeah, I know, ng-conf) no matter what, even if things are not ready.

I won't fight anymore on this, as I know I won't be listened. External people like me just have to deal with issues you don't care of. But you're taking a big risk with CLI v6. A lot of important things have been rewritten and added, and you're doing all that without the community, as last beta and RC still have no changelog, so very few crazy people like me can test. So I won't be surprised if when final is released, issues arise in all directions.

**Comment by chrste90** [comment]
Hi @cyrilletuzi ,

i just saw this commit: https://github.com/angular/angular/pull/23234/commits/c99c2177b4faf6435d571d415257a69436bde634
It looks like it is possible to set defaults for schematics like this (I didn't try it):
```
{
<content of angular.json>,
"schematics": {
    "@schematics/angular:component": {
      "inlineStyle": true,
      "prefix": "aio",
      "styleext": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "aio"
    }
}
```

Maybe it can help you with your courses until the smart defaults are working again.

**Comment by Hotell** [comment]
related 👉 https://github.com/angular/devkit/issues/520

Just pasting it here as no one from devkit team ever responded :) 👀

**Comment by cyrilletuzi** [comment]
Done a PR to fix this. Thanks @chrste90 for the direction. Thanks in advance to review this before final release.

**Comment by cyrilletuzi** [comment]
Is there is still a place in the new `angular.json` config to save the `proxyConfig` option?

**Comment by cyrilletuzi** [comment]
Found. For info in `angular.json`:

```json
"serve": {
  "options": {
    "browserTarget": "appname:build",
    "proxyConfig": "proxy.conf.json"
   }
}
```
