### ISSUE TITLE
@ngtools/webpack v1.10.2 404's as a dependency to Angular 5.2.9

### ISSUE THREAD

**Issue by tmcc1001** [angular/devkit#628]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Repro steps
1) Update @angular to v 5.2.9 from 5.2.7 in my package.json
2) run 'npm update'
3) 404's on /@ngtools/webpack/-/webpack-1.10.2.tgz

### The log given by the failure
npm ERR! fetch failed https://impulsepoint.jfrog.io/impulsepoint/api/npm/npm/@ngtools/webpack/-/webpack-1.10.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://impulsepoint.jfrog.io/impulsepoint/api/npm/npm/@ngtools/webpack/-/webpack-1.10.2.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://impulsepoint.jfrog.io/impulsepoint/api/npm/npm/@ngtools/webpack/-/webpack-1.10.2.tgz
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! fetch failed with status code 404
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\tommy_000\.npm\_logs\2018-04-05T14_15_01_409Z-debug.log

### Desired functionality
Expect the dependency to be available.

[2018-04-05T14_15_01_409Z-debug.log](https://github.com/angular/devkit/files/1880467/2018-04-05T14_15_01_409Z-debug.log)

**Comment by clydin** [comment]
According to https://www.npmjs.com/package/@ngtools/webpack that version is listed as an available version.  The error is most likely related to the use of the alternate npm registry (as shown in the above log).

**Comment by tmcc1001** [comment]
It magically worked when i retried after lunch.
