### ISSUE TITLE
Can't run RunSchematicsTask

### ISSUE THREAD

**Issue by sebawita** [angular/devkit#643]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

node: v6.9.1
npm: 5.7.1

I am also using:
```
    "@angular/cli": "1.7.4"
    "@angular-devkit/core": "~0.5.4",
    "@angular-devkit/schematics": "~0.5.4",
    "@schematics/angular": "~0.5.4",
```

### Repro steps
When I try to run another schematic using `RunSchematicsTask`, I get the following error:
```
Unregistered task "run-schematic" in schematic "add-ns".
```

Here is a code example, of how I try to call it.
```
(tree: Tree, context: SchematicContext) => {
  const options = {};
  context.addTask(new RunSchematicTask('@nativescript/schematics', 'npm-install', options));
}
```

I tried to execute my schematic by calling: `ng g add-ns`

### Mention any other details that might be useful
When I run that schematic with the following code:
```
(tree: Tree, context: SchematicContext) => schematic('npm-install', options)
```
It seems to work fine. However this approach doesn't let me wait for npm install to complete.

**Comment by hansl** [comment]
The run schematic task isn’t supported by CLI 1.7.
