### ISSUE TITLE
ng-update doesn't invoke migration schematic for @anguar/material

### ISSUE THREAD

**Issue by jelbourn** [angular/devkit#702]
### Steps to reproduce
* Clone https://github.com/jelbourn/material.angular.io/tree/ng-update-test
* Run `ng update @angular/material --next`

### Expected
The migration schematics run automatically.

### Actual
The packages update without error, but the migrate schematic isn't run. Manually running the schematic via `ng g` (specifying the collection, from, and to) works as expected.

### Versions
```
Angular CLI: 6.0.0-rc.4
Node: 8.9.4
OS: linux x64
Angular: 6.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.5.6
@angular-devkit/build-angular      0.5.6
@angular-devkit/core               0.5.6
@angular-devkit/schematics         0.5.6
@angular/cdk                       5.2.4
@angular/material                  5.2.4
@angular/material-examples         6.0.0-rc.5
@angular/material-moment-adapter   6.0.0-rc.11
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0-rc.4
@schematics/angular                0.5.6 (cli-only)
@schematics/update                 0.5.6
rxjs                               6.0.0-rc.0
typescript                         2.7.2
webpack                            4.5.0
```

**Comment by hansl** [comment]
The migration schematics for Material cover `6.0.0` updates, but Material next is current `6.0.0-rc.12`.  This means that there's no update to run. Setting the migration on an RC (anything superior to latest 5.x really) would fix the problem.

Closing as WAI.
