### ISSUE TITLE
'ng g application' clobbers existing projects

### ISSUE THREAD

**Issue by delasteve** [angular/devkit#737]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

```sh
node -v # 8.9.4
npm -v # 5.8.0
```

### Repro steps

1. `ng new foo`
2. `cd foo`
3. `ng g application foo`

### The log given by the failure

None. Notice the `angular.json` file is updated to reference the new project location using the same application name values, but `src` files are still there.

### Desired functionality

It will look to see if the project already exists in `angular.json` before creating a new project. One of two things can happen...
1. If moving from old project structure, it will move all files into the new projects structure.
2. It will guard the project and error saying project exists.

### Mention any other details that might be useful

Spoke with @filipesilva who suggested to file this as an issue.

**Comment by filipesilva** [comment]
Fixed via https://github.com/angular/devkit/pull/764, adding a project with the same name will now error out.
