### ISSUE TITLE
'stylePreprocessorOptions' does not respect the root path

### ISSUE THREAD

**Issue by delasteve** [angular/devkit#738]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

node -v # 8.9.4
npm -v # 5.8.0

### Repro steps

Assuming your in an 6.0 workspace...

1. `ng g application foo --style scss`
2. Edit `foo` application in `angular.json` to 
    ```json
    "stylePreprocessorOptions": {
      "includePaths": [
        "src/scss"
      ]
    }
    ```
3. Create a new directory, `mkdir -p projects/foo/src/scss`
4. Touch `projects/foo/src/scss/_variables.scss`
5. In `projects/foo/src/styles.scss`, add `@import 'variables';`
4. `ng build`

### The log given by the failure

```
ERROR in ./src/styles.scss (/Users/stephencavaliere/test/foo/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!/Users/stephencavaliere/test/foo/node_modules/postcss-loader/lib??embedded!/Users/stephencavaliere/test/foo/node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed:
@import 'variables';
^
      File to import not found or unreadable: variables.
      in /Users/stephencavaliere/test/foo/projects/foo/src/styles.scss (line 2, column 1)
```

### Desired functionality

The user should be able add an include path and not have to reference the relative path in scss files.

**Comment by leo6104** [comment]
Try `projects/foo/src/scss`

**Comment by delasteve** [comment]
Hmm, that works. Thanks, @leo6104!

It feels like a regression though. In 1.x projects, you were able to just specify the path relative to project root. Now you must specify everything (`index.html`, `polyfills.ts`, etc) from `projects/foo`. The `root` property is specified as `projects/foo/` which is why it feels weird to have to keep specifying part of the root path everywhere.

1.x version (edited for brevity)
```json
  "apps": [
    {
      "root": "src",
      ...
      "stylePreprocessorOptions": {
		  "includePaths": [
		    "scss"
		  ]
	  }
      ...
    }
```

**Comment by delasteve** [comment]
Spoke with @hansl about the direction of the devkit.

> paths should always be relative to the file they’re in.

With that, this issue is invalid since the solution @leo6104 provided works.
