### ISSUE TITLE
Add note to readme about snapshot builds

### ISSUE THREAD

**Issue by filipesilva** [angular/devkit#762]
We publish snapshot builds of all devkit packages, but do not mention it anywhere. We should mention this in the readme so users can take advantage of the snapshots.

**Comment by maxtacco** [comment]
Hi @filipesilva, I'm trying to install the latest build of @angular-devkit/build-ng-packagr that has custom tsconfig support. Could you please point me into the right direction?

**Comment by filipesilva** [comment]
Hi @maxtacco, you can use https://github.com/angular/angular-devkit-build-ng-packagr-builds at master.

**Comment by maxtacco** [comment]
Thank you very much! Really appreciate your quick response.
