### ISSUE TITLE
Default manifest.json is not well-formed for the app installation + inconsistency + wrong property

### ISSUE THREAD

**Issue by webmaxru** [angular/devkit#775]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
CLI RC.6

### Repro steps
ng new testApp
ng add @angular/pwa --project testApp
ng build --prod
http-server dist/testApp

Chrome -> DevTools -> Application -> Manifest -> Add to Homescreen

### The log given by the failure
**Errors:**
- Site cannot be installed: one of manifest name or short name must be specified
- Site cannot be installed: the manifest display property must be set to 'standalone' or 'fullscreen'

**Same from Lighthouse audit:**

User will not be prompted to Install the Web App
- Failures: Manifest's `display` value is not one of: minimal-ui | fullscreen | standalone, Manifest does not have `short_name`, Manifest does not have `name`.

Is not configured for a custom splash screen
- Failures: Manifest does not have `name`.

### Desired functionality
The idea to have Web App Manifest is to have the app installable. Proposed fix:
```
{
  "name": "Angular Application",
  "short_name": "Angular App",
  "display": "fullscreen",
  ...
}
```

### Theme-color insonsistency

In index.html:
```
<meta name="theme-color" content="#FFFFFF">
```
should be
```
<meta name="theme-color" content="#1976d2">
```

To follow theme_color from manifest.json as described here: https://developers.google.com/web/fundamentals/web-app-manifest/

> Specify a theme color using the theme_color property. This property sets the color of the toolbar. For this we also suggest duplicating an existing color, specifically the theme-color <meta>.

### Wrong property

```
"splash_pages": null
```
This is not a part of Web App Manifest and should be removed

https://developer.mozilla.org/en-US/docs/Web/Manifest

### References

https://developers.google.com/web/tools/lighthouse/audits/manifest-contains-short_name
Chrome's maximum recommended length is 12 characters.

CC: @Brocco

**Comment by webmaxru** [comment]
I see that `name` and `short_name` should be the title:
https://github.com/angular/devkit/blob/master/packages/angular/pwa/pwa/files/assets/manifest.json#L2

But it doesn't work in CLI RC.6

**Comment by webmaxru** [comment]
Also, Description metatag added to index.html is not about PWA. To be removed

**Comment by webmaxru** [comment]
Fixed all except `name` and `short_name` issue by https://github.com/angular/devkit/pull/776

**Comment by Brocco** [comment]
Closed via this commit: https://github.com/angular/devkit/commit/0f65111557435e65430544085b0dbd0b108bdf60
