### ISSUE TITLE
Schematics plugins for IDEs

### ISSUE THREAD

**Issue by FriOne** [angular/devkit#785]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Desired functionality
I am waiting the next release of angular and hope there will be docs for schematics. It would be convenient to have a plugin(s) to use schematics from UI. E.g. Webstorm. For example nestjs already implemented own schematics but we can use it only from command line. Is there some work in this direction? Or it will be made by community only? Does schematics have a (easy) way for IDEs to integrate schematics as a plugin?
[Jetbrains issue](https://youtrack.jetbrains.com/issue/WEB-32531)

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12115
