### ISSUE TITLE
Build Optimizer does not support es2015 code

### ISSUE THREAD

**Issue by filipesilva** [angular/devkit#816]
Build Optimizer does not currently support es2015 ~~modules~~ code, but we should support it.

Related to https://github.com/angular/devkit/pull/237

**Comment by hansl** [comment]
I was under the impression UglifyES (or whatever NG version of uglify) was doing a proper job at DCE on ES2015 code and that we wouldn't need build optimizer for those.

**Comment by cyrilletuzi** [comment]
Note: now we have Angular Elements, support for ES2015 becomes more important, because transpiling custom elements to ES5 is not supported by the standard and produces an error.

**Comment by rafaelfgx** [comment]
With all the respect, this is a very basic bug and one that should be avoided.

You create an Angular 6 application, without changing anything, with all the default settings, build it for production, and it does not work.

It is very serious that something so trivial as publishing in production is not working in the final version.

More testing is needed, especially for the most important and essential tasks.

**Comment by robwormald** [comment]
@rafaelfgx - nobody should be using es2015 modules in production, Webpack doesn’t export them, and they’re not turned on by default.

**Comment by rafaelfgx** [comment]
@robwormald, the error does not occur only with es2015.

And as I said:

You create an Angular 6 application, **without changing anything**, with all the default settings, build it for production, and it does not work.

**Comment by catull** [comment]
Hmm, I see a build optimiser bug for production builds with ES5.

See https://github.com/angular/angular-cli/issues/7799#issuecomment-389438586.
That issue is closed, stating that the bug is tracked here.

As a work-around, I switched off build-optimiser and the app is working.
With build-optimiser ON, the error is as documented in the "issue comment" at the top of this comment.

**Comment by hijamoya** [comment]
I got same issues here.

**Comment by byrondover** [comment]
> robwormald commented 10 days ago
>
> @rafaelfgx - nobody should be using es2015 modules in production, Webpack doesn’t export them, and they’re not turned on by default.

@robwormald You may want to align with @StephenFluin on your community messaging around enabling ES2015. 😅

<https://twitter.com/stephenfluin/status/997224523610116096>

P.S. Big fans of all the work you do and are doing! 🤞for production ES2015 support by 2020. :neckbeard:

**Comment by robwormald** [comment]
@byrondover ES2015 *syntax* (classes, const,let,etc) is fine (assuming your browser target supports it) - lots of good wins to be had there. 

ES2015 *modules*, not so much (though if you a very adventurous, no harm trying)

**Comment by byrondover** [comment]
Wow, didn't expect a response, let alone over Memorial Day weekend. 🇺🇸

Thanks for the clarification, gents! 🙇

**Comment by zijianhuang** [comment]
Having this problem since NG 6.0. Still a problem in 6.0.3 along with the latest CLI. As said by this others, setting "buildOptimizer":false will make things in production work again, however, the bundle is apparently too big. Let's see if 6.0.4 will has this fixed?

**Comment by filipesilva** [comment]
https://github.com/angular/devkit/pull/981 has some fixes for ES2015 code support. 

Thinking more about it, I don't do anything in regards to ES2015 modules, so that is probably enough.

**Comment by filipesilva** [comment]
Building upon #981, we should also wrap static initializers on ES2015 classes. 

This is similar to https://github.com/angular/devkit/blob/master/packages/angular_devkit/build_optimizer/README.md#wrap-enums.

The following TS class:
```
class MyClass {
  static field = console.log('hello');
}
```
transpiled to es2015 is:
```
"use strict";
class MyClass {
}
MyClass.field = console.log('hello');
//# sourceMappingURL=static.js.map
```
and ran through build optimizer yields:
```
"use strict";
class MyClass {
}
MyClass.field = /*@__PURE__*/ console.log('hello');
```

`MyClass` can never be dropped because of the property access. If we wrap it it should be ok though:

```
var MyClass = (function () {
  class MyClass {
  }
  MyClass.field = console.log('hello');
  return MyClass;
})();
```

**Comment by clydin** [comment]
Two potential downsides to this approach would be increased code size and a potential decrease in runtime performance.  Both of these should be analyzed to ensure the additional behavior is a net positive.

**Comment by zijianhuang** [comment]
As of Angular CLI 6.0.7, the problem is still there.

**Comment by filipesilva** [comment]
@zijianhuang the changes are not in 6.0.7. I think you can test these changes by installing `@angular-devkit/build-angular@0.7.0-beta.1`.

**Comment by Maximaximum** [comment]
I updated @angular-devkit to 0.6.7 and the issue seems to be gone.

**Comment by cedvdb** [comment]
issue still here with 0.7.0 and target es6.

What would be really nice is an error at compilation time as to maybe find a temporary fix for the part of the code that's problematic.

**Comment by filipesilva** [comment]
@cedvdb can you put up a repro I can look at please?

**Comment by cedvdb** [comment]
@filipesilva 

The problem seems to be resolved. I didn't manage to reproduce it yet. If you need so I could dig deeper this evening, right now I gotta work.

**Comment by filipesilva** [comment]
As long as it's working, I think there's no need to look further. If I had to bet it wasn't working because at some point you were in an old version. 

This fix is only on `@angular-devkit/build-optimizer@0.7.0-beta.1` that comes with `@angular-devkit/build-angular@0.7.0-beta.1`. 

You can check what version you have with `npm list @angular-devkit/build-optimizer`.

**Comment by shahafal** [comment]
> @StephenFluin ... things like the Google crawler  don't support ES2015

thank you for this, it's the first time i'm hearing of it. unfortunately except for discussions about this being an issue i can't find anywhere a discussion about the status to fix this.
do you know if there is an open thread in github (or someplace else) discussing the fix? i would like to follow it

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12112
