### ISSUE TITLE
build-optimizer "failing" with a 3rd dep with module.exports

### ISSUE THREAD

**Issue by Foxandxss** [angular/devkit#826]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions

Node 8, npm 5.6, windows 10

### Repro steps

https://github.com/Foxandxss/devexpress-reporting-cli-issue

The repo has all details in how to reproduce it.

In short, with build-optimizer the 3rd party package fails in prod unless I monkey patch it.

@filipesilva thinks it is work investigating from the build-optimizer standpoint.

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12111
