### ISSUE TITLE
@ngtools/webpack npm latest tag is release candidate

### ISSUE THREAD

**Issue by eseliger** [angular/devkit#836]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
macOS 10.13.4
npm 6.0.0
node 10.0.0

### Repro steps
have `@ngtools/webpack@1.10.2` installed and run `npm outdated`, the output shows something like

```
@ngtools/webpack                       1.10.2        1.10.2  6.0.0-rc.10
```

### Desired functionality

It should probably not be the `latest` but `next` version on npm

**Comment by hansl** [comment]
Just fixed. Thanks for reporting this.
