### ISSUE TITLE
Library Builder Output Optimizations

### ISSUE THREAD

**Issue by clydin** [angular/devkit#839]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Desired functionality

The library builder should support running safe build optimizer passes on built libraries as a final production build action.

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12110
