### ISSUE TITLE
ng update @angular/cli sets incorrect ngswConfigPath

### ISSUE THREAD

**Issue by CDDelta** [angular/devkit#845]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

Angular: 6.0.0

### Repro steps

Migrate an angular-cli.json app with service worker to angular.json.

### The log given by the failure

Something about ngsw-config.json not found.

### Desired functionality

ngswConfigPath should be set to `src/ngsw-config.json` not `/src/ngsw-config.json`
https://github.com/angular/devkit/blob/9bbc4e62005c150ee1f24ee15ae8abcbba8e875d/packages/schematics/angular/migrations/update-6/index.ts#L310

**Comment by chamikasandamal** [comment]
Changing `/src/ngsw-config.json` to `src/ngsw-config.json` fix the issue.

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12109
