### ISSUE TITLE
Unable to extend external schematics

### ISSUE THREAD

**Issue by vikikamath** [angular/devkit#892]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ x] schematics
```

### Versions

Node: v8.9.3
npm: 5.6.0
mac OS High Sierra

### Repro steps

Create a schematic lib `my-schematic` that includes  schematic `my-component`

```json
// collection.json

"my-component": {
   "description": "My Component",
   "extends": "@schematics/angular:component"
}
```

### The log given by the failure

```bash

  Message:
    Error: Could not find (undefined)
  Stack:
    Error: Could not find (undefined)
        at Object.getWorkspace (~/my-schematics/my-component/node_modules/@schematics/angular/utility/config.js:14:15)
       at my-schematics/my-component/node_modules/@schematics/angular/component/index.js:77:36
```
### Desired functionality

`my-schematics:my-component` should extend `@schematics/angular:component`

**Comment by ampgular** [comment]
Hi @vikikamath have you installed @schematics/angular?
At the beginning I did the same error when
`branchAndMerge(externalSchematic("@schematics/angular", "component", options))
`
For me it works, tested 5 min ago.
Hope it helps

**Comment by vikikamath** [comment]
Sorry for the trouble I should have included more information earlier.
I do have `@schematics/angular` installed as a **local** dependency.  Here is a list of my deps from `package.json`
```json
/ /  package.json
"dependencies": {
    "@angular-devkit/core": "^0.6.0",
    "@angular-devkit/schematics": "^0.6.0",
    "@schematics/angular": "^0.6.0",
    "@types/jasmine": "^2.6.0",
    "@types/node": "^8.0.31",
    "jasmine": "^2.8.0",
    "typescript": "^2.5.2"
  }
```

I updated my code to reflect your suggestion:
```json
// collection.json
schematics": {
    "my-component": {
      "description": "Delegate to Angular Component",
      "factory": "./my-component/index" 
    }
  }
```

```js
// my-component/index.ts
import { Rule, externalSchematic, branchAndMerge} from '@angular-devkit/schematics'

export default function (options: any): Rule {
    return branchAndMerge(externalSchematic("@schematics/angular", "component", options))
}
```
Running the following spec fails with same error as in my previous comment. I stole this test from `@schematics/angular:component` spec:

```js
// my-component/index_spec.ts
describe('Component Schematic', () => {
  const schematicRunner = new SchematicTestRunner(
    'my-component',
    path.join(__dirname, '../collection.json'),
  );
  const defaultOptions: any = {
    name: 'foo',
    inlineStyle: false,
    inlineTemplate: false,
    changeDetection: 'Default',
    styleext: 'css',
    spec: true,
    module: undefined,
    export: false,
    project: 'bar',
  };
  let appTree: Tree;
  beforeEach(() => {
    appTree = Tree.empty();
 });
  it('should create a component', () => {
    const options = { ...defaultOptions };
    schematicRunner.runSchematic('my-component', options, appTree);
  });
});

Still fails with same error: Could not find (undefined)

**Comment by vikikamath** [comment]
Thanks guys! I understood why I was getting this error
https://github.com/angular/devkit/blob/master/packages/schematics/angular/utility/config.ts#L496 throws this error if the workspace `path` is undefined (if it does not find `angular.json` in `Tree`) and consequently `configBuffer` is null. I wish the error was bit more clear for those onboarding to Angular.

Calling external schematic `@schematics/angular:workspace` with `workSpaceOptions` prior to calling your system under test creates `angular.json` file which gets rid of this error.

```js
tree = runner.runExternalSchematic('@schematics/angular', 'workspace', workspaceOptions)
```
Reference: https://github.com/angular/devkit/blob/master/packages/schematics/angular/component/index_spec.ts#L56
