### ISSUE TITLE
schematics does not generate help for $default argument

### ISSUE THREAD

**Issue by sandangel** [angular/devkit#908]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

macOS HS,
node: 10.1.0
npm: 6.0.1

### Repro steps

ng g c -h

### The log given by the failure

Does not generate help (description) with $default argv (`<name>` in this case)
```
usage: ng generate c <name> [options]
options:
  --change-detection (-c)
    Specifies the change detection strategy.
  --dry-run (-d)
    Run through without ...
```

### Desired functionality

Show help that written in 'description' of $default argv in schema

**Comment by Brocco** [comment]
Copied this issue to the CLI repo... angular/angular-cli#10854
