### ISSUE TITLE
Running externalSchematics in unit tests

### ISSUE THREAD

**Issue by maciejtreder** [angular/devkit#916]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Area
```
- [ x ] devkit
- [ ] schematics
```

### Versions

<pre>
@angular-devkit/core 0.6.1
node: v8.11.1
npm: 5.8.0
</pre>

### Desired functionality
For purpose of creating external libraries, to be used with ```ng-add``` I would like to be able to test my schematics within raw/fresh project created by CLI. In other words, I would like to run externalSchematic from `@angular/schematics`

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12101
