### ISSUE TITLE
pwa with angular 6 does not work

### ISSUE THREAD

**Issue by vikceo** [angular/devkit#926]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x] devkit
- [ ] schematics
```

**Comment by vikceo** [comment]
complete details: https://stackoverflow.com/questions/50361196/angular-6-pwa-does-not-work?noredirect=1#comment87741844_50361196

**Comment by alexeagle** [comment]
This issue was moved to angular/angular-cli#12099
