### ISSUE TITLE
Follow @angular/* versions 

### ISSUE THREAD

**Issue by grimly** [angular/devkit#939]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [x] schematics
```

### Desired functionality

Use the same version on both @angular framework and tools.

The change from @angular/cli was an improvement to better understand if the framework and the cli were compatible and if one should be updated. The same would make sense for the dev kit

**Comment by alexeagle** [comment]
Devkit packages aren't at the same level of maturity, and may have breaking changes since they don't expose public APIs. So to follow semver, they still have major version 0.
