### ISSUE TITLE
Make DevServerBuilder extensible

### ISSUE THREAD

**Issue by mdasberg** [angular/devkit#964]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
All

### Repro steps
```typescript
import {BrowserBuilderSchema, DevServerBuilder} from '@angular-devkit/build-angular';
import {Path, virtualFs} from '@angular-devkit/core';
import {BuilderContext} from '@angular-devkit/architect';
import * as fs from 'fs-extra';

const webpackMerge = require('webpack-merge');

export class MyDevServerBuilder extends DevServerBuilder {

    /** {@inheritDoc}. */
    constructor(context: BuilderContext) {
        super(context);
    }

    buildWebpackConfig(
        root: Path, 
        projectRoot: Path, 
        host: virtualFs.Host<fs.Stats>, 
        browserOptions: BrowserBuilderSchema
    ): any {
        return webpackMerge([
            super.buildWebpackConfig(root, projectRoot, host, browserOptions),
            { plugins: [] }
        ]);
    }
}

export default MyDevServerBuilder;
```

### Desired functionality
Able to extend or alter the webpack configuration.

### Mention any other details that might be useful
This pr extracts the functionality to a function in the simular to the BrowserBuilder: [PR](https://github.com/angular/devkit/pull/962)

**Comment by filipesilva** [comment]
The PR you put up just needs a different commit message scope, otherwise it LGTM. I also want to bring https://github.com/angular/devkit/pull/946 to your attention as it lets you do something similar on a more base scale.

**Comment by filipesilva** [comment]
Fixed via https://github.com/angular/devkit/pull/962
