### ISSUE TITLE
generated apps with wrong baseUrl as TS config --> unable to compile lazyLoaded modules

### ISSUE THREAD

**Issue by Ricard** [angular/devkit#969]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
```
Angular CLI: 6.0.3
NPM: 6.0.1
Node: 8.11.1
OS: darwin x64
Angular: 6.0.3
```

### Repro steps
[Here](https://github.com/Ricard/ng6-lazyload-issue-evidence) is a repo with the evidence. It's just an ng6 app created by CLI with one lazy loaded module, that doesn't compile. See readme for more info.

### The log given by the failure
```bash
ng serve
```

> ERROR in Could not resolve module app/lazyLoadedEvidence/lazyLoadedEvidence.module relative to /Users/Ricard/NG6Evidence/evidenceApp/src/app/app-routing.module.ts

### Desired functionality
Typescript compiler should be able to resolve the absolute path described by Angular Router loadChildren property.

### Mention any other details that might be useful
This was mentioned [on some CLI issues](https://github.com/angular/angular-cli/issues/10673)
But analyzing the issue we can see its related to the scaffold typescript configuration, therefore it is related to schematics.

I guess the issue was introduced by [this commit](https://github.com/angular/devkit/commit/33af719bad1d34cca814f59ab3c0796204af9c39)

**Comment by filipesilva** [comment]
Heya, I'll answer this issue in https://github.com/angular/angular-cli/issues/10673. It generally falls under the umbrella of a CLI issue and it's easier for other people to see the response there.
