### ISSUE TITLE
configure angular build dependecnies

### ISSUE THREAD

**Issue by seemaumesh** [angular/devkit#996]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Area
```
- [x ] devkit
- [ ] schematics
```

### Repro steps
Create a new ng project

### Desired functionality
https://npm.anvaka.com/#/view/2d/%2540angular-devkit%252Fbuild-angular
This links a whole heap of dependency, would there be a way I can specify the dependencies I need and not pull the whole world.

**Comment by alexeagle** [comment]
@StephenFluin is working with the webpack team to trim whatever dependencies we can.
That's an interesting tool, thanks for the link!
We have other reasons to work on this so I'm going to drop this issue.
